### ISSUE TITLE
Unable to edit multiple steps

### ISSUE THREAD

**Issue by DAB0mB** [Urigo/tortilla#13]
Unable to edit multiple steps.

As for now we can only edit 1 step at a time, and after it finishes rebasing we need to edit the next step and repeat the rebasing process over and over again, a heavy process which consumes lots of resources. We need the `edit` command to accept multiple steps, e.g:

```
$ npm run step -- edit 4.2 4.6 4.10
```

**Comment by darkbasic** [comment]
+ 1
Something like a in interactive rebase would be the ultimate weapon, but being able to edit multiple steps could be enough.

**Comment by DAB0mB** [comment]
Just implemented!
