### ISSUE TITLE
how to rename commit tortilla messed up

### ISSUE THREAD

**Issue by srtucker22** [Urigo/tortilla#43]
Hey @DAB0mB ,

Something weird happened during a tortilla edit and it messed up the title of `Step 1: Setup` to `Step 7: Setup`. Now tortilla doesn't recognise step 1 exists. How can I fix this commit name cleanly without breaking my tortilla project?

**Comment by DAB0mB** [comment]
Hmmm, I wonder why could it be. Anyways, what you should do would be setting strict mode off

    $ tortilla strict set 0

Which will allow you to run rebase interactive without any problem

    $ git rebase -i xxx~1

Once finished you can set the strict mode back to 1 just in case

    $ tortilla strict set 1

**Comment by srtucker22** [comment]
Worked like a charm!
